# Generated by Django 3.1.5 on 2021-01-27 10:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('linksutiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webutil',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 1, 27, 10, 18, 48, 684024, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='webutil',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
