# Generated by Django 3.1.5 on 2021-01-27 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linksutiles', '0002_auto_20210127_0718'),
    ]

    operations = [
        migrations.AddField(
            model_name='webutil',
            name='obs',
            field=models.TextField(blank=True),
        ),
    ]
