# Generated by Django 3.1.5 on 2021-01-27 11:26

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linksutiles', '0003_webutil_obs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webutil',
            name='obs',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
