# Generated by Django 3.1.5 on 2021-01-27 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linksutiles', '0004_auto_20210127_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webutil',
            name='obs',
            field=models.TextField(blank=True),
        ),
    ]
