# Generated by Django 3.1.5 on 2021-02-05 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linksutiles', '0005_auto_20210127_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webutil',
            name='nombre',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
