# Generated by Django 3.1.5 on 2021-01-20 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedimientos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='obs',
            field=models.CharField(max_length=100),
        ),
    ]
