# Generated by Django 3.1.5 on 2021-01-21 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedimientos', '0002_auto_20210120_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagen',
            field=models.ImageField(blank=True, default='static/img/proced.jpg', upload_to=''),
        ),
    ]
