# Generated by Django 3.1.5 on 2021-01-21 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedimientos', '0005_auto_20210121_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='obs',
            field=models.CharField(max_length=255),
        ),
    ]
