# Generated by Django 3.1.5 on 2021-01-25 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedimientos', '0006_auto_20210121_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagen',
            field=models.ImageField(blank=True, default='proced.jpg', upload_to='static'),
        ),
    ]
